import { getPersona, PLANNING_PERSONAS, TASK_TEMPLATE_FILE, type PersonaKey } from '../personas/registry';
import { getStack, type StackKey } from '../stacks/registry';
import type { Provider } from '../utils/manifest';

export function buildInstructionContent(
  projectName: string,
  providers: Provider[],
  generatedPersonas: PersonaKey[],
  stacks: Partial<Record<PersonaKey, StackKey[]>>
): string {
  const lines: string[] = [];

  lines.push(`# AIDE Instruction — ${projectName}`, '');
  lines.push(
    '> Generated by AIDE. This file explains how to use everything AIDE set up for this project — read it once, then keep it as a reference.',
    ''
  );

  lines.push('## Your AI team', '');

  if (generatedPersonas.length === 0) {
    lines.push('No personas have been generated yet. Fill in `AIDE_SURVEY/` and run `aide init` again.', '');
  } else {
    for (const key of generatedPersonas) {
      const persona = getPersona(key);
      lines.push(`### ${persona.label}`, '');
      lines.push(persona.description, '');

      if (providers.includes('cursor')) {
        lines.push(
          `- **Cursor:** \`.cursor/agents/${persona.agentFileName}\` — mention \`@${persona.key}\` in chat, or let Cursor delegate automatically based on the task.`
        );
      }

      if (providers.includes('claude')) {
        lines.push(
          `- **Claude Code:** \`.claude/agents/${persona.agentFileName}\` — mention \`@${persona.key}\`, or let Claude delegate automatically based on the task description.`
        );
      }

      if (persona.extraSurveyFile) {
        lines.push(`- Reads/maintains: \`docs/${persona.extraSurveyFile.fileName}\``);
      }

      if (PLANNING_PERSONAS.includes(key)) {
        lines.push(`- Writes new tasks using \`docs/${TASK_TEMPLATE_FILE}\` → saves to \`docs/tasks/<id>.md\``);
      }

      lines.push('');
    }
  }

  const hasPlanningPersona = generatedPersonas.some((key) => PLANNING_PERSONAS.includes(key));
  if (hasPlanningPersona) {
    lines.push('## Writing new tasks', '');
    lines.push('1. Customize `AIDE_SURVEY/task-template.md`, then run `aide init` to sync to `docs/task-template.md`.');
    lines.push('2. **Product Owner (`@po`)** — primary task writer: creates `docs/tasks/<id>.md` and links from `docs/backlog.md`.');
    lines.push('3. **Product Manager (`@pm`)** — roadmap owner: drafts high-level items in `docs/roadmap.md`; hands detailed tasks to PO when both are configured.');
    lines.push('4. Ask e.g. `@po Add a task for user login` or `@pm Add this to the roadmap for next sprint`.');
    lines.push('');
  }

  const programmerStacks = stacks.programmer ?? [];
  if (programmerStacks.length > 0) {
    lines.push('## Stack guidance', '');
    lines.push('The Programmer persona was configured with these stack-specific best practices:', '');

    for (const key of programmerStacks) {
      const stack = getStack(key);
      const cursorNote = providers.includes('cursor')
        ? ` — also enforced via \`.cursor/rules/stacks/${stack.fragmentFile.replace(/\.md$/, '.mdc')}\``
        : '';
      lines.push(`- **${stack.label}**${cursorNote}`);
    }

    lines.push('');
  }

  lines.push('## How this fits together', '');
  lines.push('1. `AIDE_SURVEY/` is where you describe the project — it becomes `docs/` once generated.');
  lines.push('2. Each persona agent reads the relevant `docs/*.md` files before acting.');
  lines.push('3. The existing workflow still applies: Idea → Spec → Implement → Review → QA → Done.');
  lines.push(
    '4. Personas collaborate within that pipeline — e.g. PM/PO shape the spec, Programmer implements, QA validates.'
  );
  lines.push('');

  lines.push('## Keeping this in sync', '');
  lines.push('- `aide audit` — check survey fill status, drift on generated files, and what could be added.');
  lines.push('- `aide configure` — change providers, personalities, or stacks and create any missing survey files.');
  lines.push('- `aide persona add` — add a new personality later; AIDE creates only the new survey file(s) it needs.');
  lines.push('- `aide delete` — remove all AIDE files from the project (optionally including AI instruction files).');
  lines.push('- Editing `AIDE_SURVEY/*.md` and running `aide init` again regenerates agents with the latest content.');
  lines.push('');
  lines.push('## Resetting configuration', '');
  lines.push('Use the option that matches how far you want to go back.', '');
  lines.push('### Reconfigure (keep survey and generated files)', '');
  lines.push('```powershell');
  lines.push('aide configure');
  lines.push('aide configure -y -p cursor,claude -a programmer,pm,po,designer,qa,business-analyst,marketing-specialist -s angular,node-ts,tailwind');
  lines.push('aide init -y');
  lines.push('```', '');
  lines.push('### Reset AIDE state only (keep survey files on disk)', '');
  lines.push('```powershell');
  lines.push('Remove-Item .aide\\state.json');
  lines.push('aide init');
  lines.push('```', '');
  lines.push('### Full AIDE removal', '');
  lines.push('```powershell');
  lines.push('aide delete -y');
  lines.push('aide delete -y --remove-instructions');
  lines.push('```', '');
  lines.push('## Cursor terminal: interactive prompts', '');
  lines.push(
    'Cursor\'s integrated terminal may repeat `Continue` when using arrow keys. Use `aide init -y` or `aide configure -y` to skip prompts, or type `y`/`n` and press Enter.'
  );
  lines.push('');

  return lines.join('\n');
}
